### ISSUE TITLE
Uncaught Error: invalid network (argument="network", value="any", code=INVALID_ARGUMENT, version=providers/5.0.0-beta.168)

### ISSUE THREAD

**Issue by usmane3** [aboutlo/swr-eth-tutorial#2]
I tried running but screen goes blank after I try connecting meta mask wallet.

I see this error in the debug

Uncaught Error: invalid network (argument="network", value="any", code=INVALID_ARGUMENT, version=providers/5.0.0-beta.168)

What am I missing?

**Comment by aboutlo** [comment]
hey @usmane3 this has been fixed by this  https://github.com/aboutlo/swr-eth-tutorial/pull/3.

**Comment by aboutlo** [comment]
Also, I would recommend looking here https://github.com/aboutlo/ether-swr/ because I'm not actively working on the tutorial and the new lib includes all the benefits explained in the tutorial
